### ISSUE TITLE
怎么使用Python进行像Vim那种高级命令行控制？

### ISSUE THREAD

**Issue by skyline75489** [jasonlvhit/pyoudao#1]
像 https://github.com/turingou/douban.fm 里做的这个，我想搞一个Python版本的，现在我这个 https://github.com/skyline75489/pyfm 刚开始做。

**Comment by jasonlvhit** [comment]
等我换个系统看看

**Comment by jasonlvhit** [comment]
我机器上node的douban.fm怎么跑不起来。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by jasonlvhit** [comment]
看看这里有没有你想要的：[http://docs.python-guide.org/en/latest/scenarios/cli/](http://docs.python-guide.org/en/latest/scenarios/cli/)

**Comment by skyline75489** [comment]
其实我也没装Node的那个。。。因为依赖太多了，不愿意装。。。但是人家那个看起来挺漂亮的

Python的这个能跑吗？网速好应该是没问题的，这个依赖少很多。

**Comment by jasonlvhit** [comment]
python这个没问题，超赞

**Comment by skyline75489** [comment]
找到了，应该用curses 或者 ncurses
http://www.ibm.com/developerworks/cn/linux/sdk/python/python-6/index.html

**Comment by jasonlvhit** [comment]
这个吊，有没有什么小模块我可以插一腿

**Comment by skyline75489** [comment]
现在才刚开始写，所以API还有整个程序的代码都还不稳定。主要是好多地方我都不知道怎么写。。。。。。比方说要想实现像Node写的那种界面，从头写太费劲，可能还得靠 https://github.com/wardi/urwid 这种库，如果用界面的话，可能就没办法使用mpg123的内置控制了，还得进行进程间的通信。。。

**Comment by skyline75489** [comment]
老大有什么好的想法吗？做成什么样子比较好？

**Comment by jasonlvhit** [comment]
做成node那个版本那样的就挺好哈哈，有难度才有意思

**Comment by skyline75489** [comment]
我把Last.fm Scrobble的功能加上了，我自己感觉没什么别的需求了。。。但是Bug还是不少，似乎播放的歌曲有时候会重复。。。

要想实现红心，跳过，私人电台这些功能还必须得用界面，不然不好进行控制。

**Comment by skyline75489** [comment]
监听子线程是否退出需要使用忙等待，但是用忙等待又会阻塞UI。。。哭瞎了。。。求助老大！！！

**Comment by jasonlvhit** [comment]
UI也是一个子线程？

**Comment by skyline75489** [comment]
用的urwid那个库，这个库的资料太少了，几乎没有，我只能看官方文档。官方文档里对EventLoop的介绍也不多，似乎没办法改变它的MainLoop或者往里面插入Event，要不就是我不会。。。还是看不太懂

http://urwid.org/manual/mainloop.html#widgets-displayed

**Comment by jasonlvhit** [comment]
ok，明天下午我研究研究

**Comment by skyline75489** [comment]
界面那个部分解决了，原来人家提供了一个set_alarm_in函数，可以定时进行事件唤醒。

但是还是有一些别的问题，比方说键盘的控制不好传递到播放器那里。主要还是我对这个库不熟悉。。。。
