### ISSUE TITLE
源码 Trie 树部分的疑惑

### ISSUE THREAD

**Issue by xiexiaoy** [jasonlvhit/pyoudao#2]
程序很漂亮，请教两个问题：
queryTrie 部分 print(root.child[index].child[ord('\n')].inter) 这行为何要查找到 ‘\n’ 呢
createTrie 部分 
if root.child[index]:
    root.child[index].inter = inter
    return
何种情况会执行到

**Comment by jasonlvhit** [comment]
好问题，刚从火车爬下来，两天没上github，回复有些慢，抱歉。
- 第一个问题，单步跟踪一下程序，或者看看构建好的trie树的具体元素，就能明白。
- 第二个问题，主要是当时怕有重复单词，如果有重复，会执行这句。实际上执行不到，所以去掉就可以。

**主要还是要看字典数据的具体情况**，具体问题具体分析。trie树部分我会修改一下。
